/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.tawacentral.roger.secrets;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int edit_layout=0x7f060001;
        public static final int list_access=0x7f06000e;
        public static final int list_add=0x7f06000a;
        public static final int list_container=0x7f060000;
        public static final int list_delete=0x7f06000d;
        public static final int list_description=0x7f060002;
        public static final int list_discard=0x7f06000c;
        public static final int list_email=0x7f060005;
        public static final int list_notes=0x7f060006;
        public static final int list_password=0x7f060004;
        public static final int list_save=0x7f06000b;
        public static final int list_username=0x7f060003;
        public static final int login_instructions=0x7f060009;
        public static final int login_password=0x7f060008;
        public static final int login_second_line=0x7f060007;
        public static final int reset_password=0x7f06000f;
    }
    public static final class layout {
        public static final int access_log=0x7f030000;
        public static final int list=0x7f030001;
        public static final int list_item=0x7f030002;
        public static final int login=0x7f030003;
    }
    public static final class menu {
        public static final int list_menu=0x7f050000;
        public static final int login_menu=0x7f050001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int copyright=0x7f040003;
        public static final int edit_instructions=0x7f040009;
        public static final int edit_menu_delete_secret_message=0x7f040019;
        public static final int error_reset_password=0x7f040005;
        public static final int error_save_secrets=0x7f040006;
        public static final int friendly_id_format=0x7f04000a;
        public static final int friendly_id_format_2=0x7f04000b;
        public static final int invalid_password=0x7f040004;
        public static final int list_add_secret=0x7f040013;
        public static final int list_descption_label=0x7f04000e;
        public static final int list_email_label=0x7f040011;
        public static final int list_instructions=0x7f040014;
        public static final int list_menu_access=0x7f04001e;
        public static final int list_menu_add=0x7f04001a;
        public static final int list_menu_delete=0x7f04001d;
        public static final int list_menu_discard=0x7f04001c;
        public static final int list_menu_save=0x7f04001b;
        public static final int list_name=0x7f04000c;
        public static final int list_no_data=0x7f04000d;
        public static final int list_notes_label=0x7f040012;
        public static final int list_password_label=0x7f040010;
        public static final int list_username_label=0x7f04000f;
        public static final int log_changed=0x7f040026;
        public static final int log_created=0x7f040025;
        public static final int log_min=0x7f040022;
        public static final int log_name=0x7f04001f;
        public static final int log_name_format=0x7f040020;
        /**  <string name="log_sec">{0} seconds ago</string> 
         */
        public static final int log_sec=0x7f040021;
        public static final int log_today=0x7f040023;
        public static final int log_viewed=0x7f040027;
        public static final int log_yesterday=0x7f040024;
        public static final int login_first_line=0x7f040001;
        public static final int login_instruction_1=0x7f040007;
        public static final int login_instruction_2=0x7f040008;
        public static final int login_menu_reset_password=0x7f040015;
        public static final int login_menu_reset_password_message=0x7f040016;
        public static final int login_reset_password_neg=0x7f040018;
        public static final int login_reset_password_pos=0x7f040017;
        public static final int login_second_line=0x7f040002;
    }
}
